### ISSUE TITLE
no response when bootstraping

### ISSUE THREAD

**Issue by XenGi** [squeed/nodemcu-env#1]
Wifi setup works:

```
$ ./mcutool wifi --port /dev/ttyUSB0 mywifi mypass
Configuring WiFi settings via serial...
Successfully got IP address 192.168.178.126
Now load the boostrap environment with 'boostrap'
```

Bootstraping:

```
$ ./mcutool -d bootstrap --port /dev/ttyUSB0
Flushing serial port
WRITE COMMAND: b'\r\n'
Removing any old files
WRITE COMMAND: b'file.format(); print("OK")\r\n'
Got response: file.format(); print("OK")
format done.
OK
> 
Starting fileserver
WRITE COMMAND: b'ip="127.0.1.1"; filename="init.lua"; print("OK")\r\n'
Got response: ip="127.0.1.1"; filename="init.lua"; print("OK")
OK
> 
Downloading file
WRITE COMMAND: b'sk = net.createConnection(net.TCP, 0); file.open(filename, "w+"); sk:on("receive", function(sck, c) file.write(c) ; end ); sk:on("disconnection", function(sock, a) file.flush(); file.close(); end); sk:connect(9600, ip); print("OK")\r\n'
Got response: sk = net.createConnection(net.TCP, 0); file.open(filename, "w+"); sk:on("receive", function(sck, c) file.write(c) ; end ); sk:on("disconnection", function(sock, a) file.flush(); file.close(); end); sk:connect(9600, ip); print("OK")
OK
> 

```

Then it hangs and nothing happens for at least 3min. I aborted it with `Ctrl+C`. How long should this take normally?
It hangs on the line `fs.event.wait()  # Wait for the server to say that it's done`. It got the "OK" and the lua prompt, so it should be done and continue.

I removed the `-t` in the shebang because their is no such option in the python3 interpreter and even  if I try to run it with python2 where there is such an option this shebang doesn't work and it also complains about not finding the "socketserver" module. So I think python3 is the way to go here.
You should change the shebang to `#!/usr/bin/env python3`. This will work on every os.

**Comment by squeed** [comment]
Thanks for the feedback! You're totally right about python3 - that was a silly mistake of mine.

There are couple bugs here :-(. The first is that the script is opening a socket, but only on localhost.  You can see it there when it says 'starting fileserver', then sets the ip to 127.0.0.1. This is the root cause. The second bug is that it reports everything as OK, which is clearly not true :-(.

I'll try and look in to this in the next few days. If you wanted to debug this further, try and figure out why the socketserver is binding to localhost.

**Comment by XenGi** [comment]
The binds should be `self.socket.bind(('', port))` and `server = socketserver.UDPServer(('', BROADCAST_PORT), BroadcastListener)` to bind to INADDR_ANY.

Also the line `local_ip = socket.gethostbyname(socket.gethostname())` often returns `127.0.0.1` because many distros has their hostname with this address in their `/etc/hosts` file. The best way that requires no dependencies I found to get the correct address requires an internet connection but works:

```
def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    ip = s.getsockname()[0]
    s.close()
    return ip
local_ip = get_ip_address()
```

With this fixes included it still hangs on the same point. I got some errors on the nodemcu with your commands, so I removed all `;` which are unnecessary in lua and it seemed to work but still no response in the python code.

I will continue debugging this tomorrow.

Do you have a working version of this somewhere? I thought you already used this when you told me about it in the nerd area the other day.
